# Generated by Django 5.2.7 on 2026-01-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryuser",
            name="faculty_id",
            field=models.CharField(
                blank=True,
                help_text="Faculty/Staff ID number",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="libraryuser",
            name="student_id",
            field=models.CharField(
                blank=True,
                help_text="Student ID number",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
