# Generated by Django 5.2.7 on 2026-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryuser",
            name="office_hours",
            field=models.CharField(
                blank=True,
                help_text="Office hours for staff members",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="libraryuser",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="Position or job title for staff members",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="libraryuser",
            name="specialization",
            field=models.TextField(
                blank=True,
                help_text="Area of specialization for staff members",
                null=True,
            ),
        ),
    ]
