# Generated by Django 5.2.7 on 2026-01-06 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_libraryuser_faculty_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the study room", max_length=100
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Study Room"),
                            ("group", "Group Study Room"),
                            ("presentation", "Presentation Room"),
                        ],
                        help_text="Type of study room",
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(help_text="Maximum number of people"),
                ),
                (
                    "features",
                    models.JSONField(default=list, help_text="List of room features"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the room is available for booking",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Location description", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Room",
                "verbose_name_plural": "Study Rooms",
            },
        ),
        migrations.CreateModel(
            name="StudyRoomBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                ("date", models.DateField(help_text="Booking date")),
                ("start_time", models.TimeField(help_text="Start time")),
                ("end_time", models.TimeField(help_text="End time")),
                (
                    "duration_hours",
                    models.PositiveIntegerField(help_text="Duration in hours"),
                ),
                (
                    "number_of_people",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of people using the room"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, help_text="Purpose of booking"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        help_text="Booking status",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="accounts.studyroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_room_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Room Booking",
                "verbose_name_plural": "Study Room Bookings",
                "ordering": ["date", "start_time"],
                "unique_together": {("room", "date", "start_time")},
            },
        ),
    ]
