# Generated by Django 5.2.7 on 2026-01-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_libraryuser_email_verified_emailconfirmationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryuser",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("staff", "Staff"),
                    ("public", "Public"),
                ],
                default="public",
                help_text="Type of library membership",
                max_length=20,
            ),
        ),
    ]
