# Generated by Django 5.2.7 on 2026-01-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_studyroom_studyroombooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryuser",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="QR code image for the user",
                null=True,
                upload_to="qr_codes/users/",
            ),
        ),
    ]
