# Generated by Django 4.2.7 on 2026-01-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_libraryuser_membership_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryuser",
            name="office_hours",
            field=models.CharField(
                blank=True, help_text="Office hours information", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="libraryuser",
            name="position",
            field=models.CharField(
                blank=True, help_text="Job title or position", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="libraryuser",
            name="specialization",
            field=models.JSONField(
                blank=True, default=list, help_text="List of specializations"
            ),
        ),
    ]
