# Generated by Django 5.2.7 on 2026-01-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_libraryuser_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryuser',
            name='qr_code',
        ),
    ]
