# Generated by Django 5.2.7 on 2026-01-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_libraryuser_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryuser",
            name="is_staff_approved",
            field=models.BooleanField(
                default=True,
                help_text="Whether staff membership has been approved by admin",
            ),
        ),
    ]
