# Generated by Django 5.2.7 on 2026-01-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_libraryuser_is_staff_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryuser",
            name="staff_id",
            field=models.CharField(
                blank=True,
                help_text="Staff ID number",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="libraryuser",
            name="faculty_id",
            field=models.CharField(
                blank=True,
                help_text="Faculty ID number",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
