# Generated by Django 5.2.7 on 2026-01-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_libraryuser_staff_id_alter_libraryuser_faculty_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
