# Generated by Django 5.2.7 on 2026-01-28 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the featured content", max_length=500
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Short description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Featured image",
                        null=True,
                        upload_to="featured/",
                    ),
                ),
                ("link", models.URLField(blank=True, help_text="Link URL")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the content is active"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
            ],
            options={
                "verbose_name": "Featured Content",
                "verbose_name_plural": "Featured Content",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the static page", max_length=500
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL slug for the page", unique=True),
                ),
                ("content", models.TextField(help_text="Content of the static page")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the page is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Page",
                "verbose_name_plural": "Static Pages",
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the blog post", max_length=500
                    ),
                ),
                ("content", models.TextField(help_text="Content of the blog post")),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, help_text="Date the post was published", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        help_text="Publication status of the post",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Author of the blog post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the news article", max_length=500
                    ),
                ),
                ("content", models.TextField(help_text="Content of the news article")),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, help_text="Date the news was published", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        help_text="Publication status of the news",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Author of the news article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
    ]
