# Generated by Django 5.2.7 on 2026-01-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the featured content", max_length=500
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Short description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Featured image",
                        null=True,
                        upload_to="featured/",
                    ),
                ),
                ("link", models.URLField(blank=True, help_text="Link URL")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the content is active"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
            ],
            options={
                "verbose_name": "Featured Content",
                "verbose_name_plural": "Featured Content",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the static page", max_length=500
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL slug for the page", unique=True),
                ),
                ("content", models.TextField(help_text="Content of the static page")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the page is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Page",
                "verbose_name_plural": "Static Pages",
            },
        ),
    ]
