# Generated by Django 5.2.7 on 2026-01-11 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_featuredcontent_staticpage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the news article", max_length=500
                    ),
                ),
                ("content", models.TextField(help_text="Content of the news article")),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, help_text="Date the news was published", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        help_text="Publication status of the news",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Author of the news article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
    ]
