# Generated by Django 5.2.7 on 2026-01-05 23:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "loan_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time the book was loaned",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        help_text="Date the book is due to be returned"
                    ),
                ),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date the book was actually returned",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                            ("lost", "Lost"),
                        ],
                        default="active",
                        help_text="Current status of the loan",
                        max_length=20,
                    ),
                ),
                (
                    "book_copy",
                    models.ForeignKey(
                        help_text="The specific book copy loaned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="catalog.bookcopy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who borrowed the book",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "ordering": ["-loan_date"],
            },
        ),
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount of the fine", max_digits=8
                    ),
                ),
                (
                    "reason",
                    models.CharField(help_text="Reason for the fine", max_length=200),
                ),
                (
                    "paid_date",
                    models.DateTimeField(
                        blank=True, help_text="Date the fine was paid", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                        ],
                        default="unpaid",
                        help_text="Current status of the fine",
                        max_length=20,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        help_text="The loan this fine is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fines",
                        to="circulation.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fine",
                "verbose_name_plural": "Fines",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "reservation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date the reservation was made",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(help_text="Date the reservation expires"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        help_text="Current status of the reservation",
                        max_length=20,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="The book being reserved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the reservation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
                "ordering": ["-reservation_date"],
            },
        ),
    ]
