# Generated by Django 4.2.7 on 2026-01-21 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "reservation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date the reservation was made",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(help_text="Date the reservation expires"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        help_text="Current status of the reservation",
                        max_length=20,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="The book being reserved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the reservation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
                "ordering": ["-reservation_date"],
            },
        ),
        migrations.CreateModel(
            name="LoanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date the request was made",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        help_text="Date the request expires if not processed"
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, help_text="Date the request was approved", null=True
                    ),
                ),
                (
                    "rejection_date",
                    models.DateTimeField(
                        blank=True, help_text="Date the request was rejected", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        help_text="Current status of the request",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes from staff or user"
                    ),
                ),
                (
                    "book_copy",
                    models.ForeignKey(
                        help_text="The specific book copy requested",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_requests",
                        to="catalog.bookcopy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User making the borrow request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Request",
                "verbose_name_plural": "Loan Requests",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "loan_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time the book was loaned",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        help_text="Date the book is due to be returned"
                    ),
                ),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date the book was actually returned",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                            ("lost", "Lost"),
                        ],
                        default="active",
                        help_text="Current status of the loan",
                        max_length=20,
                    ),
                ),
                (
                    "book_copy",
                    models.ForeignKey(
                        help_text="The specific book copy loaned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="catalog.bookcopy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who borrowed the book",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "ordering": ["-loan_date"],
            },
        ),
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount of the fine", max_digits=8
                    ),
                ),
                (
                    "reason",
                    models.CharField(help_text="Reason for the fine", max_length=200),
                ),
                (
                    "paid_date",
                    models.DateTimeField(
                        blank=True, help_text="Date the fine was paid", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                        ],
                        default="unpaid",
                        help_text="Current status of the fine",
                        max_length=20,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        help_text="The loan this fine is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fines",
                        to="circulation.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fine",
                "verbose_name_plural": "Fines",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Student/Staff registration number",
                        max_length=50,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the visitor", max_length=200
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department", max_length=100
                    ),
                ),
                (
                    "faculty",
                    models.CharField(blank=True, help_text="Faculty", max_length=100),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True, help_text="What did you come to the library with"
                    ),
                ),
                (
                    "check_in",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Check-in date and time",
                    ),
                ),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True, help_text="Check-out date and time", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        help_text="Current attendance status",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registered library user (null for visitors)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
                "ordering": ["-check_in"],
            },
        ),
    ]
