# Generated by Django 5.2.7 on 2026-01-06 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_book_department_book_faculty"),
        ("circulation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date the request was made",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        help_text="Date the request expires if not processed"
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, help_text="Date the request was approved", null=True
                    ),
                ),
                (
                    "rejection_date",
                    models.DateTimeField(
                        blank=True, help_text="Date the request was rejected", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        help_text="Current status of the request",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes from staff or user"
                    ),
                ),
                (
                    "book_copy",
                    models.ForeignKey(
                        help_text="The specific book copy requested",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_requests",
                        to="catalog.bookcopy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User making the borrow request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Request",
                "verbose_name_plural": "Loan Requests",
                "ordering": ["-request_date"],
            },
        ),
    ]
