# Generated by Django 5.2.7 on 2026-01-11 06:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circulation", "0002_loanrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Student/Staff registration number",
                        max_length=50,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the visitor", max_length=200
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department", max_length=100
                    ),
                ),
                (
                    "faculty",
                    models.CharField(blank=True, help_text="Faculty", max_length=100),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True, help_text="What did you come to the library with"
                    ),
                ),
                (
                    "check_in",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Check-in date and time",
                    ),
                ),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True, help_text="Check-out date and time", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        help_text="Current attendance status",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registered library user (null for visitors)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
                "ordering": ["-check_in"],
            },
        ),
    ]
