# Generated by Django 5.2.7 on 2026-01-16 13:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("repository", "0003_documentpermissionrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for these statistics", unique=True
                    ),
                ),
                (
                    "total_users",
                    models.PositiveIntegerField(
                        default=0, help_text="Total registered users"
                    ),
                ),
                (
                    "active_users",
                    models.PositiveIntegerField(
                        default=0, help_text="Users active in the last 30 days"
                    ),
                ),
                (
                    "new_users",
                    models.PositiveIntegerField(
                        default=0, help_text="New user registrations"
                    ),
                ),
                (
                    "total_books",
                    models.PositiveIntegerField(
                        default=0, help_text="Total books in catalog"
                    ),
                ),
                (
                    "available_books",
                    models.PositiveIntegerField(default=0, help_text="Available books"),
                ),
                (
                    "checked_out_books",
                    models.PositiveIntegerField(
                        default=0, help_text="Currently checked out books"
                    ),
                ),
                (
                    "total_loans",
                    models.PositiveIntegerField(default=0, help_text="Total loans"),
                ),
                (
                    "active_loans",
                    models.PositiveIntegerField(
                        default=0, help_text="Currently active loans"
                    ),
                ),
                (
                    "overdue_loans",
                    models.PositiveIntegerField(default=0, help_text="Overdue loans"),
                ),
                (
                    "returned_today",
                    models.PositiveIntegerField(
                        default=0, help_text="Books returned today"
                    ),
                ),
                (
                    "total_documents",
                    models.PositiveIntegerField(
                        default=0, help_text="Total documents in repository"
                    ),
                ),
                (
                    "document_downloads",
                    models.PositiveIntegerField(
                        default=0, help_text="Document downloads today"
                    ),
                ),
                (
                    "page_views",
                    models.PositiveIntegerField(
                        default=0, help_text="Total page views"
                    ),
                ),
                (
                    "searches",
                    models.PositiveIntegerField(default=0, help_text="Total searches"),
                ),
                (
                    "logins",
                    models.PositiveIntegerField(default=0, help_text="User logins"),
                ),
            ],
            options={
                "verbose_name": "Daily Statistics",
                "verbose_name_plural": "Daily Statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SystemHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(help_text="Average response time in seconds"),
                ),
                (
                    "cpu_usage",
                    models.FloatField(
                        blank=True, help_text="CPU usage percentage", null=True
                    ),
                ),
                (
                    "memory_usage",
                    models.FloatField(
                        blank=True, help_text="Memory usage percentage", null=True
                    ),
                ),
                (
                    "disk_usage",
                    models.FloatField(
                        blank=True, help_text="Disk usage percentage", null=True
                    ),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of errors in the last hour"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, help_text="Last error message"),
                ),
                (
                    "db_connections",
                    models.PositiveIntegerField(
                        default=0, help_text="Active database connections"
                    ),
                ),
                (
                    "db_query_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Queries executed"
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this health check was performed",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Health",
                "verbose_name_plural": "System Health",
                "ordering": ["-checked_at"],
                "get_latest_by": "checked_at",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("book_view", "Book View"),
                            ("search", "Search"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("checkout", "Book Checkout"),
                            ("return", "Book Return"),
                            ("reservation", "Reservation"),
                            ("download", "Document Download"),
                            ("registration", "User Registration"),
                        ],
                        help_text="Type of analytics event",
                        max_length=20,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Session identifier for anonymous users",
                        max_length=100,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "page_url",
                    models.URLField(blank=True, help_text="Page URL for page views"),
                ),
                (
                    "search_query",
                    models.CharField(
                        blank=True, help_text="Search query terms", max_length=500
                    ),
                ),
                ("referrer", models.URLField(blank=True, help_text="Referrer URL")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional event metadata"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        help_text="Book related to the event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="catalog.book",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document related to the event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to="repository.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the event (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Event",
                "verbose_name_plural": "Analytics Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_a_event_t_6c35be_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="analytics_a_user_id_ecb128_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_a_created_546677_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PopularItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("book", "Book"), ("document", "Document")],
                        help_text="Type of item",
                        max_length=10,
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, help_text="Number of views"),
                ),
                (
                    "checkout_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of checkouts/downloads"
                    ),
                ),
                (
                    "search_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of searches"
                    ),
                ),
                (
                    "total_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Combined popularity score"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        help_text="Book (if item_type is book)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity",
                        to="catalog.book",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document (if item_type is document)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity",
                        to="repository.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Popular Item",
                "verbose_name_plural": "Popular Items",
                "ordering": ["-total_score"],
                "unique_together": {("item_type", "book"), ("item_type", "document")},
            },
        ),
    ]
