# Generated by Django 5.2.7 on 2026-01-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the author", max_length=200
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Biography of the author"),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the department", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the department"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Department code", max_length=10, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the faculty", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the faculty"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Faculty code (e.g., SCI, ART)",
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the genre", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the genre"),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the publisher", max_length=200),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Address of the publisher"),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Website of the publisher"),
                ),
            ],
            options={
                "verbose_name": "Publisher",
                "verbose_name_plural": "Publishers",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the book", max_length=500),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text="ISBN-10 or ISBN-13", max_length=13, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the book"),
                ),
                ("publication_date", models.DateField(help_text="Publication date")),
                (
                    "edition",
                    models.CharField(
                        blank=True, help_text="Edition of the book", max_length=50
                    ),
                ),
                ("pages", models.PositiveIntegerField(help_text="Number of pages")),
                (
                    "language",
                    models.CharField(
                        default="English",
                        help_text="Language of the book",
                        max_length=50,
                    ),
                ),
                (
                    "book_file",
                    models.FileField(
                        blank=True,
                        help_text="Digital book file (PDF, EPUB, etc.)",
                        null=True,
                        upload_to="books/",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Book cover image",
                        null=True,
                        upload_to="book_covers/",
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        help_text="Authors of the book",
                        related_name="books",
                        to="catalog.author",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department the book belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="catalog.department",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        help_text="Faculty the book belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="catalog.faculty",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Genre of the book",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="catalog.genre",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        help_text="Publisher of the book",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="catalog.publisher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        help_text="Unique barcode for the copy",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        help_text="Condition of the copy",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("checked_out", "Checked Out"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                        ],
                        default="available",
                        help_text="Current status of the copy",
                        max_length=20,
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(help_text="Date the copy was acquired"),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Shelf location or storage location", max_length=100
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        help_text="The book this copy belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Copy",
                "verbose_name_plural": "Book Copies",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                help_text="Faculty this department belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="catalog.faculty",
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the topic", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the topic"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Topic code", max_length=20, unique=True
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department this topic belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="catalog.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "unique_together": {("name", "department")},
            },
        ),
        migrations.AddField(
            model_name="book",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic topic of the book",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="catalog.topic",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "faculty")},
        ),
    ]
