# Generated by Django 5.2.7 on 2026-01-06 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the faculty", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the faculty"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Faculty code (e.g., SCI, ART)",
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                help_text="Genre of the book",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="catalog.genre",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the department", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the department"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Department code", max_length=10, unique=True
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        help_text="Faculty this department belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="catalog.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "unique_together": {("name", "faculty")},
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the topic", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the topic"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Topic code", max_length=20, unique=True
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department this topic belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="catalog.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "unique_together": {("name", "department")},
            },
        ),
        migrations.AddField(
            model_name="book",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic topic of the book",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="catalog.topic",
            ),
        ),
    ]
