# Generated by Django 5.2.7 on 2026-01-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='qr_code',
        ),
    ]
