# Generated by Django 5.2.7 on 2026-01-06 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_faculty_alter_book_genre_department_topic_book_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department the book belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="catalog.department",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                help_text="Faculty the book belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="catalog.faculty",
            ),
        ),
    ]
