# Generated by Django 5.2.7 on 2026-01-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_book_department_book_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="QR code image for the book",
                null=True,
                upload_to="qr_codes/books/",
            ),
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="QR code image for the book copy",
                null=True,
                upload_to="qr_codes/copies/",
            ),
        ),
    ]
