# Generated by Django 5.2.7 on 2026-01-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_book_qr_code_bookcopy_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_file",
            field=models.FileField(
                blank=True,
                help_text="Digital book file (PDF, EPUB, etc.)",
                null=True,
                upload_to="books/",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Book cover image",
                null=True,
                upload_to="book_covers/",
            ),
        ),
    ]
