# Generated by Django 4.2.7 on 2026-01-21 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the collection", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the collection"
                    ),
                ),
                (
                    "curator",
                    models.ForeignKey(
                        blank=True,
                        help_text="User responsible for curating this collection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curated_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.CreateModel(
            name="EBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the eBook", max_length=500),
                ),
                (
                    "authors",
                    models.TextField(
                        help_text="Authors of the eBook (comma-separated)"
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True, help_text="Abstract or summary of the eBook"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file", upload_to="repository/"
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date the eBook was uploaded"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("open", "Open Access"),
                            ("restricted", "Restricted"),
                            ("embargo", "Embargoed"),
                            ("private", "Private"),
                        ],
                        default="open",
                        help_text="Access level for the eBook",
                        max_length=20,
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        help_text="Collection this eBook belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ebooks",
                        to="repository.collection",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the eBook",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_ebooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "eBook",
                "verbose_name_plural": "eBooks",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="EBookPermissionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for requesting access to this eBook"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Status of the permission request",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was reviewed", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the admin review"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the request was made"
                    ),
                ),
                (
                    "ebook",
                    models.ForeignKey(
                        blank=True,
                        help_text="The eBook access is being requested for",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_requests",
                        to="repository.ebook",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The staff user requesting access",
                        limit_choices_to={"groups__name": "Staff"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ebook_permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "eBook Permission Request",
                "verbose_name_plural": "eBook Permission Requests",
                "ordering": ["-requested_at"],
                "unique_together": {("ebook", "user")},
            },
        ),
        migrations.CreateModel(
            name="EBookPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        default=True, help_text="Whether access is granted or revoked"
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the permission was granted"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about why access was granted",
                    ),
                ),
                (
                    "ebook",
                    models.ForeignKey(
                        blank=True,
                        help_text="The eBook being granted access to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="repository.ebook",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who granted this permission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The staff user being granted access",
                        limit_choices_to={"groups__name": "Staff"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ebook_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "eBook Permission",
                "verbose_name_plural": "eBook Permissions",
                "ordering": ["-granted_at"],
                "unique_together": {("ebook", "user")},
            },
        ),
    ]
