# Generated by Django 5.2.7 on 2026-01-15 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0002_documentpermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPermissionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for requesting access to this document"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Status of the permission request",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was reviewed", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the admin review"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the request was made"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document access is being requested for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_requests",
                        to="repository.document",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The staff user requesting access",
                        limit_choices_to={"groups__name": "Staff"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Permission Request",
                "verbose_name_plural": "Document Permission Requests",
                "ordering": ["-requested_at"],
                "unique_together": {("document", "user")},
            },
        ),
    ]
