# Generated by Django 4.2.7 on 2026-01-21 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repository", "0004_rename_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ebook",
            options={
                "ordering": ["-upload_date"],
                "verbose_name": "eBook",
                "verbose_name_plural": "eBooks",
            },
        ),
        migrations.AlterModelOptions(
            name="ebookpermission",
            options={
                "ordering": ["-granted_at"],
                "verbose_name": "eBook Permission",
                "verbose_name_plural": "eBook Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="ebookpermissionrequest",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "eBook Permission Request",
                "verbose_name_plural": "eBook Permission Requests",
            },
        ),
        migrations.AlterUniqueTogether(
            name="ebookpermission",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="ebookpermissionrequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ebookpermission",
            name="ebook",
            field=models.ForeignKey(
                blank=True,
                help_text="The eBook being granted access to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="repository.ebook",
            ),
        ),
        migrations.AddField(
            model_name="ebookpermissionrequest",
            name="ebook",
            field=models.ForeignKey(
                blank=True,
                help_text="The eBook access is being requested for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_requests",
                to="repository.ebook",
            ),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="abstract",
            field=models.TextField(
                blank=True, help_text="Abstract or summary of the eBook"
            ),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("open", "Open Access"),
                    ("restricted", "Restricted"),
                    ("embargo", "Embargoed"),
                    ("private", "Private"),
                ],
                default="open",
                help_text="Access level for the eBook",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="authors",
            field=models.TextField(help_text="Authors of the eBook (comma-separated)"),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                help_text="Collection this eBook belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ebooks",
                to="repository.collection",
            ),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="title",
            field=models.CharField(help_text="Title of the eBook", max_length=500),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="upload_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date the eBook was uploaded"
            ),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded the eBook",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_ebooks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ebookpermission",
            name="user",
            field=models.ForeignKey(
                help_text="The staff user being granted access",
                limit_choices_to={"groups__name": "Staff"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ebook_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ebookpermissionrequest",
            name="reason",
            field=models.TextField(
                help_text="Reason for requesting access to this eBook"
            ),
        ),
        migrations.AlterField(
            model_name="ebookpermissionrequest",
            name="user",
            field=models.ForeignKey(
                help_text="The staff user requesting access",
                limit_choices_to={"groups__name": "Staff"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ebook_permission_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ebookpermission",
            unique_together={("ebook", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="ebookpermissionrequest",
            unique_together={("ebook", "user")},
        ),
        migrations.RemoveField(
            model_name="ebookpermission",
            name="document",
        ),
        migrations.RemoveField(
            model_name="ebookpermissionrequest",
            name="document",
        ),
    ]
